server:
  port: 8090
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
     active:
       - "qa"

build:
  version: "3.0"

loans:
  message: "Welcome to Lvgod loans related local APIs"
  contactDetails:
    name: "Ssa Andarabi -Developer"
    email: "ssa.andarabi@lvgod.com"
  onCallSupport:
      -(031) 555-123-1234
      -(031) 555-123-1235