spring:
  application:
    name: "configserver"
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
        #native:
          #search-locations: "classpath:/config"
         #search-locations: "file:///D://Projects//IntellijWorkspace//config"
        git:
          uri: "https://github.com/mrandarabski/lvgod.git"
          default-label: main
          timeout: 5
          clone-one-start: true
          force-pull: true
    rabbitmq:
      host: "localhost"
      port: 5672
      username: "guest"
      password: "quest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
    endpoint:
      health:
        probes:
          enabled: true

encrypt:
  key: "fcIZOFYWLuE9YROUQQaLyHSFG6SP3H3s"

server:
  port: 8071